FROM appsody/nodejs:0.3

RUN useradd --gid 0 --create-home node_user \
 && mkdir -p /project/user-app/node_modules \
 && chown -R node_user:0 /project/user-app/node_modules

ENV APPSODY_MOUNTS=.:/project/user-app
ENV APPSODY_DEPS=/project/user-app/node_modules

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/node_modules;/project/user-app/dist
ENV APPSODY_WATCH_REGEX="^.*.ts$"

# LoopBack 4 applications require 'npm run build' to transpile TypeScript source code
ENV APPSODY_PREP="npm install --prefix user-app && npm run build --prefix user-app"

ENV APPSODY_RUN="npm run pretest --prefix user-app && npm start"
ENV APPSODY_RUN_ON_CHANGE="npm run pretest --prefix user-app && npm start"
ENV APPSODY_RUN_KILL=true

ENV APPSODY_DEBUG="npm run debug"
ENV APPSODY_DEBUG_ON_CHANGE="npm run pretest --prefix user-app && npm run debug"
ENV APPSODY_DEBUG_KILL=true

ENV APPSODY_TEST="npm test && npm test --prefix user-app"
ENV APPSODY_TEST_ON_CHANGE=""
ENV APPSODY_TEST_KILL=false

COPY ./LICENSE /licenses/
COPY ./project /project
COPY --chown=node_user:0 ./config /config

WORKDIR /project
RUN npm install \
 && npm run pretest

RUN chown -R node_user:0 /project

USER node_user

ENV PORT=3000
ENV NODE_PATH=/project/user-app/node_modules

EXPOSE 3000
EXPOSE 9229
