language: generic

go:
  - 1.12.x

os: linux
dist: bionic

before-install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - apt-cache madison docker-ce

matrix:
  include:
    - services: docker
    - install: sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce 
    - if: $(. ./ci/minimum_docker_version.sh)!=""
      install: sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=$(. ./ci/minimum_docker_version.sh)

before-script: 
  - docker --version
  - ./ci/download_cli.sh

script:
  - . ./ci/build.sh


# note before_deploy will run before each deploy provider
before_deploy:
  - . ./ci/release.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: ci/release/*
  file_glob: true
  on:
    tags: true
    repo: appsody/stacks
    branch: master
